# Generated by Django 2.1.7 on 2019-04-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='课程名称')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Teacher')),
            ],
        ),
    ]
