# Generated by Django 2.2.1 on 2019-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190619_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default='未知', max_length=10, verbose_name='年龄'),
        ),
    ]
